server:
  port: 8080
  servlet:
    context-path: /ruike
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
#      是否自动提交
      enable-auto-commit: true
#      自动提交频率---3000毫秒
      auto-commit-interval: 3000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/tables?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
  mail:
    host: smtp.qq.com
    port : 465
    username: 229849575@qq.com
#    不能直接写QQ密码，而是授权码
    password: joondicnspnxbjhg
    protocol: smtps
#    采用SSL安全链接
    properties:
      mail:
        smtp:
          ssl:
            enable: true

#Redis
  redis:
    database: 11
    host: localhost
    port: 6379


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
#  写了这个路径之后，我们在mapper.xml映射文件中不需要写出实体类的完整路径（namespace），只需要写出类名即可

  configuration:
#    插入数据后，进行数据返回包装，比如添加一个用户之后，再把这个用户查询返回封装
#    !!!!注意!!!!  在mapper.xml映射文件里的SQL语句标签里，一定要制定主键，这样主键才能返回过来
    use-generated-keys: true
#    开启驼峰命名
    map-underscore-to-camel-case: true
#
community:
  path:
    domain: http://localhost:8080
    upload: d:/work/data/upload



